import 'package:flutter/material.dart';
import 'constants/color_constants.dart';
import 'widgets/add_message_section.dart';
import 'widgets/chat_section.dart';

import 'widgets/auto_generated_replay_section.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController animationController;
  bool isAutoReplyListShowen = false;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 300));
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final bottom = MediaQuery.of(context).viewInsets.bottom;
    if (bottom > 0 && !isAutoReplyListShowen) {
      isAutoReplyListShowen = true;
      Future.delayed(const Duration(milliseconds: 300)).then((value) {
        animationController.forward();
      });
    }

    if (bottom == 0) {
      animationController.reverse();
      isAutoReplyListShowen = false;
    }
  }

  @override
  void dispose() {
    super.dispose();
    animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Yuppo App',
          style: TextStyle(color: Colors.white),
        ),
        centerTitle: true,
        backgroundColor: ColorConstants.primaryColor,
      ),
      body: Column(
        children: [
          // chat part
          const ChatSection(),
          // part of the quick responses and the adding message
          Column(
            children: [
              if (isAutoReplyListShowen)
                FadeTransition(
                  opacity: animationController,
                  child: const AutoGeneratedReplySection(),
                ),
              const AddMessageSection(),
            ],
          ),
        ],
      ),
    );
  }
}
