import 'package:flutter/material.dart';

import '../constants/list_constants.dart';
import 'auto_message_widget.dart';

class AutoGeneratedReplySection extends StatelessWidget {
  const AutoGeneratedReplySection({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 30,
      child: ListView.builder(
        itemCount: ListConstants.autoReplyMessages.length,
        padding: const EdgeInsets.symmetric(horizontal: 10),
        scrollDirection: Axis.horizontal,
        itemBuilder: (ctx, index) =>
            AutoMessageWidget(message: ListConstants.autoReplyMessages[index]),
      ),
    );
  }
}
